# docker run -ti --rm \
#       -e DISPLAY=$DISPLAY \
#       -v /tmp/.X11-unix:/tmp/.X11-unix \
#       --device /dev/video0 \
#       object_detector_app


version: '2'
services:
  bot:
    build: bot
    privileged: true
    ports:
      - "80:8001"

  base:
    build: raspberry-pi-python-opencv

#  camera:
#    build: camera
#    privileged: true
#    ports:
#      - "8080:8080"

#  camera:
#    build:
#      context: .
#      args:
#        WHL_URL: http://ci.tensorflow.org/view/Nightly/job/nightly-pi/lastSuccessfulBuild/artifact/output-artifacts/
#        WHL_FILE: tensorflow-1.9.0rc0-cp27-none-linux_armv7l.whl
#    devices:
#       - /dev/video0
#       - /dev/dri
#    ports:
#      - "8080:8080"

  redis:
    build: redis
    command: redis-server --protected-mode no
    ports:
      - "6379"

