# docker run -ti --rm \
#       -e DISPLAY=$DISPLAY \
#       -v /tmp/.X11-unix:/tmp/.X11-unix \
#       --device /dev/video0 \
#       object_detector_app


version: '3'
services:
  object_detector_app:
    build: .
    devices:
       - /dev/video0
       - /dev/dri
       - /dev/snd
    environment:
       - DISPLAY
       - QT_X11_NO_MITSHM=1
    volumes:
       - /etc/localtime:/etc/localtime:ro
       - /tmp/.X11-unix:/tmp/.X11-unix
    expose:
      - "8080"
