# docker run -ti --rm \
#       -e DISPLAY=$DISPLAY \
#       -v /tmp/.X11-unix:/tmp/.X11-unix \
#       --device /dev/video0 \
#       object_detector_app


version: '2'
services:
  bot:
    build: bot

  object_detector_app:
    build: .
    devices:
       - /dev/video0
       - /dev/dri
    ports:
      - "8080:8080"

  redis:
    image: redis:4-alpine
    ports:
      - "6379:6379"

